apiVersion: v1
kind: Service
metadata:
  name: zookeeper
  labels:
    app: zookeeper
spec:
  ports:
    - name: zookeeper
      port: 2181
      targetPort: 2181
  selector:
    app: zookeeper
  type: ClusterIP

---
apiVersion: v1
kind: Service
metadata:
  name: kafka-service
  labels:
    app: kafka
spec:
  ports:
    - name: kafka-port
      port: 9092
      targetPort: 9092
  selector:
    app: kafka
  type: ClusterIP

---
apiVersion: v1
kind: Service
metadata:
  name: eureka-service
  labels:
    app: eureka
spec:
  ports:
    - name: eureka
      port: 8761
      targetPort: 8761
  selector:
    app: eureka
  type: LoadBalancer

---
apiVersion: v1
kind: Service
metadata:
  name: api-gateway
  labels:
    app: gateway
spec:
  ports:
    - name: gateway-port
      port: 80
      targetPort: 80
  selector:
    app: gateway
  type: LoadBalancer

---
apiVersion: v1
kind: Service
metadata:
  name: admin-service
  labels:
    app: admin
spec:
  ports:
    - name: admin
      port: 8082
      targetPort: 8082
  selector:
    app: admin
  type: ClusterIP

---
apiVersion: v1
kind: Service
metadata:
  name: chat-service
  labels:
    app: chat
spec:
  ports:
    - name: chat
      port: 8083
      targetPort: 8083
  selector:
    app: chat
  type: ClusterIP

---
apiVersion: v1
kind: Service
metadata:
  name: lawyer-service
  labels:
    app: lawyer
spec:
  ports:
    - name: lawyer
      port: 8081
      targetPort: 8081
  selector:
    app: lawyer
  type: ClusterIP

---
apiVersion: v1
kind: Service
metadata:
  name: manage-service
  labels:
    app: manage
spec:
  ports:
    - name: manage
      port: 8084
      targetPort: 8084
  selector:
    app: manage
  type: ClusterIP

---
apiVersion: v1
kind: Service
metadata:
  name: user-service
  labels:
    app: user
spec:
  ports:
    - name: user
      port: 8085
      targetPort: 8085
  selector:
    app: user
  type: ClusterIP
